### PR TITLE
Scale.alpha_continuous & Scale.alpha_discrete

### LINKED ISSUE #1226: opacity in the color scale
this fails:

```
colorx = RGBA(0.0,0.5,0,0.1)
colory = RGBA(0,0.5,0,1.0)
plot(x=[1,2,3], y=[2,6,4], Geom.point(),  Scale.color_continuous(colormap=Scale.lab_gradient(colorx, colory)))

ERROR: StackOverflowError:
Stacktrace:
 [1] lab_gradient(::ColorTypes.RGBA{Float64}, ::Vararg{ColorTypes.RGBA{Float64},N} where N) at /Users/monty/.julia/v0.6/Gadfly/src/color_misc.jl:71 (repeats 20947 times)
```

How i can make it work?

### LINKED ISSUE #1242: svgjs, hstack and opacity
In the v1.0.1 docs, the left plot for [`Geom.ribbon`](http://gadflyjl.org/stable/gallery/geometries/#[Geom.ribbon](@ref)-1) currently has a non-transparent ribbon (mentioned in #1241). I can reproduce this by doing:
```julia
# p1 and p2 from the docs Geom.ribbon example
draw(SVGJS("Docs_ribbon.svg"), hstack(p1,p2))
```
SVGJS seems to be the only backend with this issue; the issue didn't occur for me using other backends. SVG is fine.

### PR DESCRIPTION
**Pull request by Mattriks**
- [x] I've updated the documentation to reflect these changes
- [x] I've added an entry to `NEWS.md`
- [x] I've added and/or updated the unit tests
- [x] I've run the regression tests
- [x] I've built the docs and confirmed these changes don't cause new errors

Same as #1252, but now with `alpha` info in the docstrings for `Geom.point`, `Geom.polygon` and `Geom.ribbon` 

- fixes #1226, fixes #1242

### CODE REVIEW

File: src/scale.jl [hunk 1]
```diff
@@ -313,7 +325,7 @@ anything in the data that's not respresented in `levels` will be set to
 default order.
 
 See also [`group_discrete`](@ref), [`shape_discrete`](@ref), 
-[`size_discrete`](@ref), and [`linestyle_discrete`](@ref).
+[`size_discrete`](@ref), and [`linestyle_discrete`](@ref), and [`alpha_discrete`](@ref).
```
Comment (bjarthur) [inline src/scale.jl]: the "and" before linestyle_discrete could be removed as it was in #1252

File: src/geom/polygon.jl [hunk 2]
```diff
@@ -69,20 +70,25 @@ function render(geom::PolygonGeometry, theme::Gadfly.Theme, aes::Gadfly.Aestheti
...
+    alphas = Vector{Float64}(undef, n)
+    alpha_discrete  = AT <: Int
+
     for (k,g) in enumerate(ug)
         i = groups.==[g]
         polys[k] = polygon_points(aes_x[i], aes_y[i], geom.preserve_order)
         colors[k] = first(aes_color[i])
-        line_styles[k] = mod1(first(aes_linestyle[i]), linestyle_palette_length) 
+        line_styles[k] = mod1(first(aes_linestyle[i]), linestyle_palette_length)
+        alphas[k] = first(alpha_discrete ? theme.alphas[aes_alpha[i]] : aes_alpha[i])
```
Comment (bjarthur) [inline src/geom/polygon.jl]: what git weirdness is causing the `line_style[k]` line to be highlight as a change?

File: src/geom/ribbon.jl [hunk 3]
```diff
@@ -10,41 +10,42 @@ RibbonGeometry(default_statistic=Gadfly.Stat.identity(); fill=true, tag=empty_ta
     Geom.ribbon
 
 Draw a ribbon at the positions in `x` bounded above and below by `ymax` and
-`ymin`, respectively.  Optionally draw multiple ribbons by grouping with `color`.
+`ymin`, respectively.  Optionally draw multiple ribbons by grouping with `color` and `alpha` or `linestyle`.
```
Comment (bjarthur) [inline src/geom/ribbon.jl]: what does "color and alpha or linestyle" mean?  the boolean logic is unclear

File: test/testscripts/scale_alpha_discrete.jl [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+    Theme(alphas=[0.5], discrete_highlight_color=identity,
+        point_size=2mm)
+)
+p2 = plot(D, x=:x, y=:y, alpha=:x, shape=:Shape, coord,
+    Scale.alpha_discrete, Geom.point, Geom.hair,
+    Guide.title("Scale.alpha_discrete, Theme(default_color=\"green\")"),
+    Theme(default_color="green",   discrete_highlight_color=c->"gray",
+        point_size=2mm, alphas=[0.0,0.2,0.4,0.6,0.8,1.0])
+)
+hstack(p1,p2)
```
Comment (bjarthur) [inline test/testscripts/scale_alpha_discrete.jl]: both of these tests are near identical to the docs, the only difference being the hard-coded random numbers.  seems redundant.  ideally i like to see real data, say from RDatasets, used in the docs that is particularly pretty, and very simple made up cases for the tests with focus on execution speed (we time out sometimes) and code coverage.  this is a bit of a nit-pick, but can you at least make the docs and the tests less redundant?

File: src/scale.jl (hunk 1 above)
Comment (Mattriks) [reply src/scale.jl]: Done

File: src/geom/ribbon.jl (hunk 3 above)
Comment (Mattriks) [reply src/geom/ribbon.jl]: I've clarified this. It differs whether the ribbon is filled or not filled:
https://github.com/GiovineItalia/Gadfly.jl/blob/99f54e467e92c6478dea5ef3ec68ae4bfe30377e/src/geom/ribbon.jl#L75-L76

File: test/testscripts/scale_alpha_discrete.jl (hunk 4 above)
Comment (Mattriks) [reply test/testscripts/scale_alpha_discrete.jl]: I like this example because it illustrates e.g. "color aesthetic, fixed alpha" and "alpha aesthetic, fixed color".  If I used an example from RDatasets to illustrate the `alpha` aesthetic, I would use something like the `Diamonds` dataset (53940 points).  In my next PR I'm going to halve the time it takes to plot that: `Geom.point` currently suffers from using a new context for every point.

File: src/geom/polygon.jl (hunk 2 above)
Comment (Mattriks) [reply src/geom/polygon.jl]: Weird - no idea.
