### PR TITLE
Stat.smooth() confidence bands

### LINKED ISSUE #559: Geom.ribbon in does not accept Int vectors as input when used with Geom.smooth
Geom.ribbon does't accept Int vectors as input for ymin and ymax when used in combination with Geom.smooth.

http://stackoverflow.com/questions/28966555/geom-ribbon-in-gadfly-julia-does-not-accept-int-vectors-as-input

### LINKED ISSUE #1167: Order dependent incorrect handling of NaN in Geom.ribbon
Ran into a bug with `Geom.ribbon` where if `ymin`/`ymax` are first `NaN` then concrete values, the concrete values are ignored. However, if the concrete values appear first then it works correctly.

```julia
using Gadfly
srand(123);
ys = rand(20)
plot(x=repeat(1:10, outer=2), y=ys, ymin=ys.-1, ymax=ys.+1, color=repeat([:a,:b], inner=10), Geom.line, Geom.ribbon)
```

image

### Concrete values first

```julia
ys2 = copy(ys)
ys2[11:end] = NaN
plot(x=repeat(1:10, outer=2), y=ys2, ymin=ys2.-1, ymax=ys2.+1, color=repeat([:a,:b], inner=10), Geom.line, Geom.ribbon)
```
image

### NaN values first

The expect behavior here is `Geom.ribbon` showing the yellow values

```julia
ys2 = copy(ys)
ys2[1:10] = NaN
plot(x=repeat(1:10, outer=2), y=ys2, ymin=ys2.-1, ymax=ys2.+1, color=repeat([:a,:b], inner=10), Geom.line, Geom.ribbon)
```
image

### PR DESCRIPTION
**Pull request by Mattriks**
- [x] I've updated the documentation to reflect these changes
- [x] I've added an entry to `NEWS.md`
- [x] I've added and/or updated the unit tests
- [x] I've run the regression tests
- [x] I've built the docs and confirmed these changes don't cause new errors

### This PR:
- Adds confidence bands for `Stat.smooth(method=:lm)` 
    (but not for `method=:loess`, because currently Loess.jl doesn't return the loess standard error #519)
- Updates `Geom.ribbon` (fixes #1167, closes #559)
- Adds gallery examples for `Stat.smooth()`

### Examples
```julia
salaries = dataset("car","Salaries")
salaries.Salary /= 1000.0
salaries.Discipline = ["Discipline $(x)" for x in salaries.Discipline] 

p = plot(salaries[salaries.Rank.=="Prof",:], x=:YrsService, y=:Salary, 
    color=:Sex, xgroup = :Discipline,
    Geom.subplot_grid(Geom.point,
     layer(Stat.smooth(method=:lm, levels=[0.95, 0.99]), Geom.line, Geom.ribbon)), 
    Scale.xgroup(levels=["Discipline A", "Discipline B"]),
    Guide.colorkey(title="", pos=[0.43w, -0.4h]), 
    Theme(point_size=2pt,
        lowlight_color=c->RGBA{Float32}(c.r, c.g, c.b, 0.2) )
)
```
stat_smooth1

```julia
x = range(0.1, stop=4.9, length=30)
D = DataFrame(x=x, y=x.+randn(length(x)))

p = plot(D, x=:x, y=:y, Geom.point,
     layer(Stat.smooth(method=:lm, levels=[0.90,0.99]), Geom.line, Geom.ribbon(fill=false)),
     Theme(lowlight_color=c->"gray", line_style=[:solid, :dot])
)
```
stat_smooth2

### CODE REVIEW

File: src/misc.jl [hunk 1]
```diff
@@ -32,9 +32,9 @@ function concretize(xss::AbstractVector...)
         @label next_j1
     end
 
-    yss = Array{AbstractVector}(length(xss))
+    yss = Vector{AbstractVector}(undef, length(xss))
     for (i, xs) in enumerate(xss)
-        yss[i] = Array{eltype(xs)}(count)
+        yss[i] = Vector{eltype(xs)}(undef, count)
```
Comment (bjarthur) [inline src/misc.jl]: wow, how did you find this omission?  would be great to add a unit test, as codevec is reporting that this codepath is still not tested.

Comment (tlnagy) [reply src/misc.jl]: Ouch that must've slipped by us when we updated everything for 1.0. We need a unit test there ASAP

Comment (Mattriks) [reply src/misc.jl]: I'll add a unit test to this PR. I found this omission while investigating #1167, after restyling `Geom.ribbon`.

**Comment by Mattriks** [comment]
Added a unit test (in testscripts/nan_skipping.jl), rebased and squashed commits - done!
